"""Change latest_review_date to Date type

Revision ID: 94ab5b20ca87
Revises: 
Create Date: 2026-01-12 03:38:42.924188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94ab5b20ca87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.alter_column('latest_review_date',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('prod_attributes1',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='鎵撴爣瀛楁?1',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes2',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='鎵撴爣瀛楁?2',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes3',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='鎵撴爣瀛楁?3',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes4',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='鎵撴爣瀛楁?4',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes5',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='鎵撴爣瀛楁?5',
               existing_nullable=True)
        batch_op.alter_column('_rule_matched',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='鎵撴爣鐘舵?,LABELED琛ㄧず宸叉墦鏍',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_brand'))
        batch_op.drop_index(batch_op.f('idx_category'))
        batch_op.drop_index(batch_op.f('idx_category_brand'))
        batch_op.drop_index(batch_op.f('idx_eRetailer'), mysql_length={'eRetailer': 50})
        batch_op.drop_index(batch_op.f('idx_is_competitor'), mysql_length={'is_competitor': 50})
        batch_op.drop_index(batch_op.f('idx_last_month_total'), mysql_length={'last_month_total': 20})
        batch_op.drop_index(batch_op.f('idx_last_total_comments'), mysql_length={'last_total_comments': 20})
        batch_op.drop_index(batch_op.f('idx_latest_review_date'), mysql_length={'latest_review_date': 50})
        batch_op.drop_index(batch_op.f('idx_online_store'), mysql_length={'online_store': 50})
        batch_op.drop_index(batch_op.f('idx_prod_attributes1'), mysql_length={'prod_attributes1': 50})
        batch_op.drop_index(batch_op.f('idx_prod_attributes2'), mysql_length={'prod_attributes2': 50})
        batch_op.drop_index(batch_op.f('idx_prod_attributes3'), mysql_length={'prod_attributes3': 50})
        batch_op.drop_index(batch_op.f('idx_prod_attributes4'), mysql_length={'prod_attributes4': 50})
        batch_op.drop_index(batch_op.f('idx_prod_attributes5'), mysql_length={'prod_attributes5': 50})
        batch_op.drop_index(batch_op.f('idx_rule_brand'), mysql_length={'brand': 50, '_rule_matched': 20})
        batch_op.drop_index(batch_op.f('idx_rule_category'), mysql_length={'category': 50, '_rule_matched': 20})
        batch_op.drop_index(batch_op.f('idx_rule_matched'))
        batch_op.drop_index(batch_op.f('idx_total'), mysql_length={'total': 20})
        batch_op.drop_index(batch_op.f('idx_total_comments'), mysql_length={'total_comments': 20})
        batch_op.create_index(batch_op.f('ix_sample_data__rule_matched'), ['_rule_matched'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_data_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_data_category'), ['category'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='鏍锋湰鏁版嵁琛'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='鐢ㄦ埛ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='鐢ㄦ埛鍚',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='瀵嗙爜(鍔犲瘑瀛樺偍)',
               existing_nullable=False)
        batch_op.alter_column('real_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='鐪熷疄濮撳悕',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('Data_admin', 'BU_admin', 'Labeller'),
               comment=None,
               existing_comment='瑙掕壊',
               existing_nullable=False)
        batch_op.alter_column('category_arr',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='category鏉冮檺鏁扮粍,NULL=鍏ㄩ儴鏉冮檺',
               existing_nullable=True)
        batch_op.alter_column('brand_arr',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='brand鏉冮檺鏁扮粍,NULL=鍏ㄩ儴鏉冮檺',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='璐﹀彿鏄?惁婵?椿',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.drop_table_comment(
        existing_comment='鐢ㄦ埛琛'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '鐢ㄦ埛琛',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='璐﹀彿鏄?惁婵?椿',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('brand_arr',
               existing_type=mysql.JSON(),
               comment='brand鏉冮檺鏁扮粍,NULL=鍏ㄩ儴鏉冮檺',
               existing_nullable=True)
        batch_op.alter_column('category_arr',
               existing_type=mysql.JSON(),
               comment='category鏉冮檺鏁扮粍,NULL=鍏ㄩ儴鏉冮檺',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('Data_admin', 'BU_admin', 'Labeller'),
               comment='瑙掕壊',
               existing_nullable=False)
        batch_op.alter_column('real_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='鐪熷疄濮撳悕',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment='瀵嗙爜(鍔犲瘑瀛樺偍)',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='鐢ㄦ埛鍚',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='鐢ㄦ埛ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.create_table_comment(
        '鏍锋湰鏁版嵁琛',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_sample_data_category'))
        batch_op.drop_index(batch_op.f('ix_sample_data_brand'))
        batch_op.drop_index(batch_op.f('ix_sample_data__rule_matched'))
        batch_op.create_index(batch_op.f('idx_total_comments'), ['total_comments'], unique=False, mysql_length={'total_comments': 20})
        batch_op.create_index(batch_op.f('idx_total'), ['total'], unique=False, mysql_length={'total': 20})
        batch_op.create_index(batch_op.f('idx_rule_matched'), ['_rule_matched'], unique=False)
        batch_op.create_index(batch_op.f('idx_rule_category'), ['category', '_rule_matched'], unique=False, mysql_length={'category': 50, '_rule_matched': 20})
        batch_op.create_index(batch_op.f('idx_rule_brand'), ['brand', '_rule_matched'], unique=False, mysql_length={'brand': 50, '_rule_matched': 20})
        batch_op.create_index(batch_op.f('idx_prod_attributes5'), ['prod_attributes5'], unique=False, mysql_length={'prod_attributes5': 50})
        batch_op.create_index(batch_op.f('idx_prod_attributes4'), ['prod_attributes4'], unique=False, mysql_length={'prod_attributes4': 50})
        batch_op.create_index(batch_op.f('idx_prod_attributes3'), ['prod_attributes3'], unique=False, mysql_length={'prod_attributes3': 50})
        batch_op.create_index(batch_op.f('idx_prod_attributes2'), ['prod_attributes2'], unique=False, mysql_length={'prod_attributes2': 50})
        batch_op.create_index(batch_op.f('idx_prod_attributes1'), ['prod_attributes1'], unique=False, mysql_length={'prod_attributes1': 50})
        batch_op.create_index(batch_op.f('idx_online_store'), ['online_store'], unique=False, mysql_length={'online_store': 50})
        batch_op.create_index(batch_op.f('idx_latest_review_date'), ['latest_review_date'], unique=False, mysql_length={'latest_review_date': 50})
        batch_op.create_index(batch_op.f('idx_last_total_comments'), ['last_total_comments'], unique=False, mysql_length={'last_total_comments': 20})
        batch_op.create_index(batch_op.f('idx_last_month_total'), ['last_month_total'], unique=False, mysql_length={'last_month_total': 20})
        batch_op.create_index(batch_op.f('idx_is_competitor'), ['is_competitor'], unique=False, mysql_length={'is_competitor': 50})
        batch_op.create_index(batch_op.f('idx_eRetailer'), ['eRetailer'], unique=False, mysql_length={'eRetailer': 50})
        batch_op.create_index(batch_op.f('idx_category_brand'), ['category', 'brand'], unique=False)
        batch_op.create_index(batch_op.f('idx_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('idx_brand'), ['brand'], unique=False)
        batch_op.alter_column('_rule_matched',
               existing_type=mysql.VARCHAR(length=255),
               comment='鎵撴爣鐘舵?,LABELED琛ㄧず宸叉墦鏍',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes5',
               existing_type=mysql.VARCHAR(length=255),
               comment='鎵撴爣瀛楁?5',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes4',
               existing_type=mysql.VARCHAR(length=255),
               comment='鎵撴爣瀛楁?4',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes3',
               existing_type=mysql.VARCHAR(length=255),
               comment='鎵撴爣瀛楁?3',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes2',
               existing_type=mysql.VARCHAR(length=255),
               comment='鎵撴爣瀛楁?2',
               existing_nullable=True)
        batch_op.alter_column('prod_attributes1',
               existing_type=mysql.VARCHAR(length=255),
               comment='鎵撴爣瀛楁?1',
               existing_nullable=True)
        batch_op.alter_column('latest_review_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
