"""add note column to sample_data

Revision ID: ba90b0a2e4b6
Revises: 94ab5b20ca87
Create Date: 2026-01-12 06:28:37.068255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba90b0a2e4b6'
down_revision = '94ab5b20ca87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_data', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
